train_data_file: ../datasets/credit_01/train.gz
test_data_file: ../datasets/credit_01/test.gz
oot_data_file: ../datasets/credit_01/oot.gz

output_oot_file: 'data/credit_01_oot.gz'

id_var: ID
date_var: REF_DATE
ym_var: REF
target_var: TARGET
age_var: IDADE